
[general]

	[general.music_disc]
		music_disc = false

	[general.fishing_timer]
		fishing_timer = false
		fishing_timer_size = 2

	[general.category]
		color_picker = "255,255,0,0"

	[general.rage_on_death]
		rage_in_dungeons = false
		rage_on_death = false

	[general.mute_own_steps]
		mute_own_steps = false

[random]

	[random.dynamic_fov]
		dynamic_fov = false
		normal_fov = 100

	[random.music_disc]
		music_disc = false

	[random.rage_on_death]
		rage_in_dungeons = false
		rage_on_death = false

[music_disc]

	[music_disc.music_disc]
		music_disc = false

[skyblock]

	[skyblock.fishing_timer]
		fishing_timer = false
		fishing_timer_size = 0

	[skyblock.mineshaft_party]
		warp_settings = 2
		mineshaft_party = true

[qol]

	[qol.slumber_hotel]
		slumber_hotel = true

	[qol.remove_particles]
		remove_particles = true
		sponge = true
		glyphs = true

	[qol.lucky_block_enhancements]
		lucky_block_enhancements = false

	[qol.better_tab]
		better_tab = false

	[qol.out_of_arrows_reminder]
		out_of_arrows_reminder = false

	[qol.jump_boost_reminder]
		jump_boost_reminder = true

	[qol.mining_fatigue_reminder]
		mining_fatigue_reminder = true

	[qol.mute_own_steps]
		mute_own_steps = false

